# auto merging PR from dependabot 
name: Dependabot auto-merge

on: 
  workflow_run:
    workflows:
      - PR Title Checker
      - Lint
      - Tests
    types: 
      - completed
    branches: 
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.TOKEN }}"

      - name: Get PR URL
        uses: kceb/pull-request-url-action@v2
        id: pr-url

      - run: echo "${{ steps.pr-url.outputs.url }}"

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge --squash "${{ steps.pr-url.outputs.url }}"