name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  execute-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        id: cache-node
        with:
          node-version: 20
          cache: "npm"

      - name: Store Playwright version to env variable
        run: |
          PLAYWRIGHT_VERSION=$(cat package.json \
          | grep @playwright/test \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[", ^]//g')

          echo "Playwright version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Node env
        run: npm ci

      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Execute tests
        run: |
          echo "Executing tests now..."

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30

      # - name: Test Passed
      #   if: success()
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     disable_web_page_preview: true
      #     format: markdown
      #     message: |
      #       Tests have *PASSED*.

      #       Branch name: ${{ env.BRANCH_NAME }} - [check the workflow on this link.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      # - name: Test Failed
      #   if: failure()
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     disable_web_page_preview: true
      #     format: markdown
      #     message: |
      #       Tests have *FAILED*.

      #       Branch name: ${{ env.BRANCH_NAME }} - [check the workflow on this link.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
